import type { RankLevel } from '../database/types';

export interface RankCardTheme {
  key: string;
  order: number;
  name: string;
  surfaceStart: string;
  surfaceEnd: string;
  border: string;
  accent: string;
  textPrimary: string;
  textSecondary: string;
  badgeBackground: string;
  badgeText: string;
  badgeBorder: string;
  avatarRing: string;
  focusRing: string;
  shadow: string;
  isDark: boolean;
}

/**
 * 17 Military & Youth Union Emulation Rank Card Themes
 * Progressive gradient tint, WCAG AA compliant (4.5:1 contrast for text),
 * subtle & professional for modern projector and classroom displays.
 */
export const RANK_CARD_THEMES: Record<number, RankCardTheme> = {
  1: {
    key: 'slate',
    order: 1,
    name: 'Binh nhì',
    surfaceStart: '#F8FAFC',
    surfaceEnd: '#EEF2F6',
    border: '#CBD5E1',
    accent: '#64748B',
    textPrimary: '#0F172A',
    textSecondary: '#475569',
    badgeBackground: '#F1F5F9',
    badgeText: '#334155',
    badgeBorder: '#CBD5E1',
    avatarRing: '#94A3B8',
    focusRing: '#64748B',
    shadow: 'rgba(100, 116, 139, 0.08)',
    isDark: false,
  },
  2: {
    key: 'steel',
    order: 2,
    name: 'Binh nhất',
    surfaceStart: '#F5F7FA',
    surfaceEnd: '#E8EDF3',
    border: '#BCC8D6',
    accent: '#53657A',
    textPrimary: '#0F172A',
    textSecondary: '#475569',
    badgeBackground: '#EDF2F7',
    badgeText: '#334155',
    badgeBorder: '#BCC8D6',
    avatarRing: '#8E9EAF',
    focusRing: '#53657A',
    shadow: 'rgba(83, 101, 122, 0.08)',
    isDark: false,
  },
  3: {
    key: 'ice',
    order: 3,
    name: 'Hạ sĩ',
    surfaceStart: '#F0F9FF',
    surfaceEnd: '#E0F2FE',
    border: '#BAE6FD',
    accent: '#0369A1',
    textPrimary: '#0C4A6E',
    textSecondary: '#0369A1',
    badgeBackground: '#E0F2FE',
    badgeText: '#075985',
    badgeBorder: '#7DD3FC',
    avatarRing: '#38BDF8',
    focusRing: '#0284C7',
    shadow: 'rgba(3, 105, 161, 0.08)',
    isDark: false,
  },
  4: {
    key: 'cyan',
    order: 4,
    name: 'Trung sĩ',
    surfaceStart: '#ECFEFF',
    surfaceEnd: '#CFFAFE',
    border: '#A5F3FC',
    accent: '#0E7490',
    textPrimary: '#164E63',
    textSecondary: '#0E7490',
    badgeBackground: '#CFFAFE',
    badgeText: '#155E75',
    badgeBorder: '#67E8F9',
    avatarRing: '#22D3EE',
    focusRing: '#0891B2',
    shadow: 'rgba(14, 116, 144, 0.08)',
    isDark: false,
  },
  5: {
    key: 'teal',
    order: 5,
    name: 'Thượng sĩ',
    surfaceStart: '#F0FDFA',
    surfaceEnd: '#CCFBF1',
    border: '#99F6E4',
    accent: '#0F766E',
    textPrimary: '#134E4A',
    textSecondary: '#0F766E',
    badgeBackground: '#CCFBF1',
    badgeText: '#115E59',
    badgeBorder: '#5EEAD4',
    avatarRing: '#2DD4BF',
    focusRing: '#0D9488',
    shadow: 'rgba(15, 118, 110, 0.08)',
    isDark: false,
  },
  6: {
    key: 'jade',
    order: 6,
    name: 'Thiếu úy',
    surfaceStart: '#ECFDF5',
    surfaceEnd: '#D1FAE5',
    border: '#A7F3D0',
    accent: '#047857',
    textPrimary: '#064E3B',
    textSecondary: '#047857',
    badgeBackground: '#D1FAE5',
    badgeText: '#065F46',
    badgeBorder: '#6EE7B7',
    avatarRing: '#34D399',
    focusRing: '#059669',
    shadow: 'rgba(4, 120, 87, 0.08)',
    isDark: false,
  },
  7: {
    key: 'green',
    order: 7,
    name: 'Trung úy',
    surfaceStart: '#F0FDF4',
    surfaceEnd: '#DCFCE7',
    border: '#BBF7D0',
    accent: '#15803D',
    textPrimary: '#14532D',
    textSecondary: '#15803D',
    badgeBackground: '#DCFCE7',
    badgeText: '#166534',
    badgeBorder: '#86EFAC',
    avatarRing: '#4ADE80',
    focusRing: '#16A34A',
    shadow: 'rgba(21, 128, 61, 0.08)',
    isDark: false,
  },
  8: {
    key: 'olive',
    order: 8,
    name: 'Thượng úy',
    surfaceStart: '#F7FEE7',
    surfaceEnd: '#ECFCCB',
    border: '#D9F99D',
    accent: '#4D7C0F',
    textPrimary: '#365314',
    textSecondary: '#4D7C0F',
    badgeBackground: '#ECFCCB',
    badgeText: '#3F6212',
    badgeBorder: '#BEF264',
    avatarRing: '#A3E635',
    focusRing: '#65A30D',
    shadow: 'rgba(77, 124, 15, 0.08)',
    isDark: false,
  },
  9: {
    key: 'sand',
    order: 9,
    name: 'Đại úy',
    surfaceStart: '#FFFBEB',
    surfaceEnd: '#FEF3C7',
    border: '#FDE68A',
    accent: '#B45309',
    textPrimary: '#78350F',
    textSecondary: '#B45309',
    badgeBackground: '#FEF3C7',
    badgeText: '#92400E',
    badgeBorder: '#FCD34D',
    avatarRing: '#FBBF24',
    focusRing: '#D97706',
    shadow: 'rgba(180, 83, 9, 0.08)',
    isDark: false,
  },
  10: {
    key: 'bronze',
    order: 10,
    name: 'Thiếu tá',
    surfaceStart: '#FFF7ED',
    surfaceEnd: '#FFEDD5',
    border: '#FED7AA',
    accent: '#C2410C',
    textPrimary: '#7C2D12',
    textSecondary: '#C2410C',
    badgeBackground: '#FFEDD5',
    badgeText: '#9A3412',
    badgeBorder: '#FDBA74',
    avatarRing: '#FB923C',
    focusRing: '#EA580C',
    shadow: 'rgba(194, 65, 12, 0.08)',
    isDark: false,
  },
  11: {
    key: 'copper',
    order: 11,
    name: 'Trung tá',
    surfaceStart: '#FFF8F1',
    surfaceEnd: '#FDE6D4',
    border: '#F4B98A',
    accent: '#A6461B',
    textPrimary: '#713116',
    textSecondary: '#A6461B',
    badgeBackground: '#FDE6D4',
    badgeText: '#873413',
    badgeBorder: '#F09958',
    avatarRing: '#E87A38',
    focusRing: '#C8521E',
    shadow: 'rgba(166, 70, 27, 0.08)',
    isDark: false,
  },
  12: {
    key: 'rosewood',
    order: 12,
    name: 'Thượng tá',
    surfaceStart: '#FFF1F2',
    surfaceEnd: '#FFE4E6',
    border: '#FECDD3',
    accent: '#BE123C',
    textPrimary: '#881337',
    textSecondary: '#BE123C',
    badgeBackground: '#FFE4E6',
    badgeText: '#9F1239',
    badgeBorder: '#FDA4AF',
    avatarRing: '#FB7185',
    focusRing: '#E11D48',
    shadow: 'rgba(190, 18, 60, 0.08)',
    isDark: false,
  },
  13: {
    key: 'plum',
    order: 13,
    name: 'Đại tá',
    surfaceStart: '#FDF4FF',
    surfaceEnd: '#FAE8FF',
    border: '#F5D0FE',
    accent: '#A21CAF',
    textPrimary: '#701A75',
    textSecondary: '#A21CAF',
    badgeBackground: '#FAE8FF',
    badgeText: '#86198F',
    badgeBorder: '#F0ABFC',
    avatarRing: '#E879F9',
    focusRing: '#C026D3',
    shadow: 'rgba(162, 28, 175, 0.08)',
    isDark: false,
  },
  14: {
    key: 'violet',
    order: 14,
    name: 'Thiếu tướng',
    surfaceStart: '#F5F3FF',
    surfaceEnd: '#EDE9FE',
    border: '#DDD6FE',
    accent: '#6D28D9',
    textPrimary: '#4C1D95',
    textSecondary: '#6D28D9',
    badgeBackground: '#EDE9FE',
    badgeText: '#5B21B6',
    badgeBorder: '#C4B5FD',
    avatarRing: '#A78BFA',
    focusRing: '#7C3AED',
    shadow: 'rgba(109, 40, 217, 0.08)',
    isDark: false,
  },
  15: {
    key: 'indigo',
    order: 15,
    name: 'Trung tướng',
    surfaceStart: '#EEF2FF',
    surfaceEnd: '#E0E7FF',
    border: '#C7D2FE',
    accent: '#4338CA',
    textPrimary: '#312E81',
    textSecondary: '#4338CA',
    badgeBackground: '#E0E7FF',
    badgeText: '#3730A3',
    badgeBorder: '#A5B4FC',
    avatarRing: '#818CF8',
    focusRing: '#4F46E5',
    shadow: 'rgba(67, 56, 202, 0.08)',
    isDark: false,
  },
  16: {
    key: 'sapphire',
    order: 16,
    name: 'Thượng tướng',
    surfaceStart: '#EFF6FF',
    surfaceEnd: '#DBEAFE',
    border: '#BFDBFE',
    accent: '#1D4ED8',
    textPrimary: '#1E3A8A',
    textSecondary: '#1D4ED8',
    badgeBackground: '#DBEAFE',
    badgeText: '#1E40AF',
    badgeBorder: '#93C5FD',
    avatarRing: '#60A5FA',
    focusRing: '#2563EB',
    shadow: 'rgba(29, 78, 216, 0.08)',
    isDark: false,
  },
  17: {
    key: 'royal',
    order: 17,
    name: 'Đại tướng',
    surfaceStart: '#0F172A',
    surfaceEnd: '#1E293B',
    border: '#F59E0B',
    accent: '#FBBF24',
    textPrimary: '#F8FAFC',
    textSecondary: '#FCD34D',
    badgeBackground: '#334155',
    badgeText: '#FDE68A',
    badgeBorder: '#F59E0B',
    avatarRing: '#F59E0B',
    focusRing: '#FBBF24',
    shadow: 'rgba(245, 158, 11, 0.16)',
    isDark: true,
  },
};

export const NEUTRAL_RANK_CARD_THEME: RankCardTheme = {
  key: 'neutral',
  order: 0,
  name: 'Chưa xếp hạng',
  surfaceStart: '#FFFFFF',
  surfaceEnd: '#F8FAFC',
  border: '#E2E8F0',
  accent: '#94A3B8',
  textPrimary: '#1E293B',
  textSecondary: '#64748B',
  badgeBackground: '#F1F5F9',
  badgeText: '#475569',
  badgeBorder: '#E2E8F0',
  avatarRing: '#CBD5E1',
  focusRing: '#3B82F6',
  shadow: 'rgba(0, 0, 0, 0.04)',
  isDark: false,
};

/**
 * Pure deterministic selector resolving RankCardTheme from RankLevel or level number
 */
export function getRankCardTheme(levelOrRank?: number | RankLevel | null): RankCardTheme {
  if (levelOrRank === null || levelOrRank === undefined) {
    return NEUTRAL_RANK_CARD_THEME;
  }

  const level = typeof levelOrRank === 'number' ? levelOrRank : levelOrRank.level;
  if (!level || typeof level !== 'number' || level < 1 || level > 17) {
    return NEUTRAL_RANK_CARD_THEME;
  }

  return RANK_CARD_THEMES[level] || NEUTRAL_RANK_CARD_THEME;
}

/**
 * Helper to generate inline CSS Custom Properties for card styling
 */
export function getRankCardStyle(theme: RankCardTheme): React.CSSProperties {
  return {
    '--rank-surface-start': theme.surfaceStart,
    '--rank-surface-end': theme.surfaceEnd,
    '--rank-border': theme.border,
    '--rank-accent': theme.accent,
    '--rank-text-primary': theme.textPrimary,
    '--rank-text-secondary': theme.textSecondary,
    '--rank-badge-bg': theme.badgeBackground,
    '--rank-badge-text': theme.badgeText,
    '--rank-badge-border': theme.badgeBorder,
    '--rank-avatar-ring': theme.avatarRing,
    '--rank-focus-ring': theme.focusRing,
    '--rank-shadow': theme.shadow,
  } as React.CSSProperties;
}
